### ISSUE TITLE
This awesome package is hidden, need SEO or something

### ISSUE THREAD

**Issue by cercata** [patricksurry/pysimconnect#1]
I found this awesome module in the MSFS forums, I wanted to write there how awesome it is, compared to the other one available, but the forum tells me it's read only.

Making searchs on google and the MSFS forum, it's quite difficult to reach here, the other package allwais arises. Even making an explicit search about "pysimconnect" google shows me the results for "simconnect" by default.

I'm trying to add bHaptics support to MSFS, and tried first with the other module, and I was thinking on giving up because simconnect was to slow (300ms for 8 vars), then I found this package, and I started getting the data I wanted faster than what I needed. Awesome.

**Comment by patricksurry** [comment]
Thanks for the feedback ❤️    The slowness watching multiple vars was why I ended up reimplementing it.    Good point on the discoverability, probably in part because it's new, but also looks like I forgot to add tags in the config file.  Now updated at https://pypi.org/project/pysimconnect/  and appears in search for `simconnect`: https://pypi.org/search/?q=simconnect

**Comment by patricksurry** [comment]
btw, you need to do a bit of onboarding in the MSFS forums before it lets you reply to posts.  if you interact with the little bot there (message in your inbox?) for a few minutes it will add privileges.

**Comment by cercata** [comment]
> btw, you need to do a bit of onboarding in the MSFS forums before it lets you reply to posts. if you interact with the little bot there (message in your inbox?) for a few minutes it will add privileges.

I'm there since the first Beta, I can write everywhere except that topic

**Comment by patricksurry** [comment]
wow, that's weird
