### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by lmk2021** [patricksurry/pysimconnect#6]
I try to install on Windows 11 following the Quick Start Guide
**pip install pysimconnect** runs with no issue.
But **simconnect --install-completion powershell** runs into the following error

(testfs) PS C:\Users\martin> simconnect --install-completion powershell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\martin\testfs\Scripts\simconnect.exe\__main__.py", line 4, in <module>
  File "C:\Users\martin\testfs\Lib\site-packages\simconnect\cli.py", line 2, in <module>
    from . import _typerpatch
  File "C:\Users\martin\testfs\Lib\site-packages\simconnect\_typerpatch.py", line 7, in <module>
    from typer.utils import _get_click_major
ImportError: cannot import name '_get_click_major' from 'typer.utils' (C:\Users\martin\testfs\Lib\site-packages\typer\utils.py)

Did I miss something?
Thank´s a lot for any hint

**Comment by patricksurry** [comment]
Hmm, i haven't tried the install for a while.  I suspect this is because `typer` has been bumped since I last shipped.

I would guess that downgrading to `typer 0.4` *might* work but I can take a look later today.  That would mean something like:

```
pip uninstall typer
pip install typer==0.4.2
```

and then try the `simconnect --install-completion powershell` again.

The rest of the package should work regardless, sorry for the hiccup.

**Comment by lmk2021** [comment]
That´s it
Thank you very much!

**Comment by patricksurry** [comment]
fixed in release 0.2.5
